// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.mayflower.filmmarket.domain;

import de.mayflower.filmmarket.domain.ShortFormIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ShortFormIntegrationTest_Roo_Configurable {
    
    declare @type: ShortFormIntegrationTest: @Configurable;
    
}
