// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.mayflower.filmmarket.domain;

import de.mayflower.filmmarket.domain.ShortForm;
import de.mayflower.filmmarket.domain.ShortFormDataOnDemand;
import de.mayflower.filmmarket.domain.ShortFormIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ShortFormIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ShortFormIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ShortFormIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ShortFormIntegrationTest: @Transactional;
    
    @Autowired
    private ShortFormDataOnDemand ShortFormIntegrationTest.dod;
    
    @Test
    public void ShortFormIntegrationTest.testCountShortForms() {
        Assert.assertNotNull("Data on demand for 'ShortForm' failed to initialize correctly", dod.getRandomShortForm());
        long count = ShortForm.countShortForms();
        Assert.assertTrue("Counter for 'ShortForm' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ShortFormIntegrationTest.testFindShortForm() {
        ShortForm obj = dod.getRandomShortForm();
        Assert.assertNotNull("Data on demand for 'ShortForm' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ShortForm' failed to provide an identifier", id);
        obj = ShortForm.findShortForm(id);
        Assert.assertNotNull("Find method for 'ShortForm' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ShortForm' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ShortFormIntegrationTest.testFindAllShortForms() {
        Assert.assertNotNull("Data on demand for 'ShortForm' failed to initialize correctly", dod.getRandomShortForm());
        long count = ShortForm.countShortForms();
        Assert.assertTrue("Too expensive to perform a find all test for 'ShortForm', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ShortForm> result = ShortForm.findAllShortForms();
        Assert.assertNotNull("Find all method for 'ShortForm' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ShortForm' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ShortFormIntegrationTest.testFindShortFormEntries() {
        Assert.assertNotNull("Data on demand for 'ShortForm' failed to initialize correctly", dod.getRandomShortForm());
        long count = ShortForm.countShortForms();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ShortForm> result = ShortForm.findShortFormEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ShortForm' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ShortForm' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ShortFormIntegrationTest.testFlush() {
        ShortForm obj = dod.getRandomShortForm();
        Assert.assertNotNull("Data on demand for 'ShortForm' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ShortForm' failed to provide an identifier", id);
        obj = ShortForm.findShortForm(id);
        Assert.assertNotNull("Find method for 'ShortForm' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyShortForm(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ShortForm' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ShortFormIntegrationTest.testMergeUpdate() {
        ShortForm obj = dod.getRandomShortForm();
        Assert.assertNotNull("Data on demand for 'ShortForm' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ShortForm' failed to provide an identifier", id);
        obj = ShortForm.findShortForm(id);
        boolean modified =  dod.modifyShortForm(obj);
        Integer currentVersion = obj.getVersion();
        ShortForm merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ShortForm' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ShortFormIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ShortForm' failed to initialize correctly", dod.getRandomShortForm());
        ShortForm obj = dod.getNewTransientShortForm(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ShortForm' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ShortForm' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'ShortForm' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ShortFormIntegrationTest.testRemove() {
        ShortForm obj = dod.getRandomShortForm();
        Assert.assertNotNull("Data on demand for 'ShortForm' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ShortForm' failed to provide an identifier", id);
        obj = ShortForm.findShortForm(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ShortForm' with identifier '" + id + "'", ShortForm.findShortForm(id));
    }
    
}
